### ISSUE TITLE
Can't find container 16 on last revision osrs

### ISSUE THREAD

**Issue by Andrflor** [guthix/Jagex-Store-5#4]
Hello,
I'm trying to use the library to decode the osrs cache for last revision.
I get this error:

`15:36:25.212 [main] DEBUG io.guthix.cache.js5.container.disk.Js5DiskStore - Reading index file 255 container 14
15:36:25.213 [main] DEBUG io.guthix.cache.js5.container.disk.Js5DiskStore - Reading index file 255 container 15
15:36:25.213 [main] WARN io.guthix.cache.js5.container.disk.Js5DiskStore - Could not read index file 255 container 16 because the index does not exist
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at io.netty.buffer.EmptyByteBuf.readUnsignedByte(EmptyByteBuf.java:534)
	at io.guthix.cache.js5.container.Js5Container$Companion.decode(Js5Container.kt:111)
	at io.guthix.cache.js5.container.Js5Container$Companion.decode$default(Js5Container.kt:110)
	at io.guthix.cache.js5.container.heap.Js5HeapStore$Companion.open(Js5HeapStore.kt:61)`

Has I understand the lib does not support last revision at the moment.
I am willing to contribute but I have only little comprehension of osrs cache format.

Do you have any clue or idea on how to fix that issue?
Thx

**Comment by Andrflor** [comment]
I fixed it myself...

**Comment by Bartvhelvert** [comment]
Hi Andrflor,

Can you post the code that you used to load the cache?
I tried to load the cache released on 08/04/2020 rev 189 and it works fine for me.
Also, what OS and Java version are you using?

**Comment by Andrflor** [comment]
Hey,
After checks gamepack was missing some archive parts...
Works fine when i just ignore missing parts..
